- name: Crear carpeta compartida para FB
  file:
    path: "{{ fb_data_dir }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: ejecutar contenedor FileBrowser
  community.docker.docker_container:
    name: "{{ fb_container_name }}"
    image: "{{ fb_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ fb_port }}:80"
    volumes:
      - "{{ fb_data_dir }}:/srv"